### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by jimc1200**
I need this in order to do pip install. Thank you!

### CODE REVIEW

**Comment by jimms** [comment]
Thank you for sending the patch to this project.

However, the file `README.md` is encoded by `utf8` not `cp950`. Does changing the encoding from `cp950` to `utf-8` works for you?

**Comment by jimc1200** [comment]
Hi~ I ran into a UnicodeDecodeError while using pip install
After looking at the error and doing some research, I though that maybe it would work if I changed that line of code?
Here is a snapshot of the error.
Thank you so much!
error

**Comment by jimc1200** [comment]
Alright, it works now! Thank you so much!

________________________________
寄件者: Jimms Hsieh <notifications@github.com>
寄件日期: 2018年12月3日 下午 09:47:16
收件者: jimms/twder
副本: 鄧吉瀚; Author
主旨: Re: [jimms/twder] Update setup.py (#1)


I have updated a new version for trying to solve your problem. Please try to install again. If it doesn't work, please try to change your terminal encoding to utf8. Thanks

**Comment by jimms** [comment]
I am glad to hear that 😸

**Pull request closed without merging**
